/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admins/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admins_list"];
        put?: never;
        post: operations["admins_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admins/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admins_retrieve"];
        put: operations["admins_update"];
        post?: never;
        delete: operations["admins_destroy"];
        options?: never;
        head?: never;
        patch: operations["admins_partial_update"];
        trace?: never;
    };
    "/api/agents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agents_list"];
        put?: never;
        post: operations["agents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agents_retrieve"];
        put: operations["agents_update"];
        post?: never;
        delete: operations["agents_destroy"];
        options?: never;
        head?: never;
        patch: operations["agents_partial_update"];
        trace?: never;
    };
    "/api/agents/profile/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agents_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_list"];
        put?: never;
        post: operations["customers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_retrieve"];
        put: operations["customers_update"];
        post?: never;
        delete: operations["customers_destroy"];
        options?: never;
        head?: never;
        patch: operations["customers_partial_update"];
        trace?: never;
    };
    "/api/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_list"];
        put?: never;
        post: operations["items_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_retrieve"];
        put: operations["items_update"];
        post?: never;
        delete: operations["items_destroy"];
        options?: never;
        head?: never;
        patch: operations["items_partial_update"];
        trace?: never;
    };
    "/api/items/by-qr/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_by_qr_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/item-size/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_item_size_list"];
        put?: never;
        post: operations["items_item_size_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/item-size/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_item_size_retrieve"];
        put: operations["items_item_size_update"];
        post?: never;
        delete: operations["items_item_size_destroy"];
        options?: never;
        head?: never;
        patch: operations["items_item_size_partial_update"];
        trace?: never;
    };
    "/api/items/variants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_variants_list"];
        put?: never;
        post: operations["items_variants_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/variants/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["items_variants_retrieve"];
        put: operations["items_variants_update"];
        post?: never;
        delete: operations["items_variants_destroy"];
        options?: never;
        head?: never;
        patch: operations["items_variants_partial_update"];
        trace?: never;
    };
    "/api/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders_list"];
        put?: never;
        post: operations["orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/add-item/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_add_item_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/delete-item/{item_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["orders_delete_item_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders_retrieve"];
        put: operations["orders_update"];
        post?: never;
        delete: operations["orders_destroy"];
        options?: never;
        head?: never;
        patch: operations["orders_partial_update"];
        trace?: never;
    };
    "/api/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description An Api View which provides a method to request a password reset token based on an e-mail address
         *
         *     Sends a signal reset_password_token_created when a reset token was created
         */
        post: operations["password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/password/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description An Api View which provides a method to reset a password based on a unique token */
        post: operations["password_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/password/validate_token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description An Api View which provides a method to verify that a token is valid */
        post: operations["password_validate_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddOrderItemRequest: {
            /** Format: uuid */
            qr_code: string;
            quantity: number;
            variant: number;
            size: number;
        };
        Admin: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
        };
        AdminRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            password: string;
        };
        Agent: {
            readonly id: number;
            readonly user: components["schemas"]["AgentUser"];
            contact: string;
            readonly total_customers: string;
        };
        AgentRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            contact: string;
        };
        AgentUser: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            role?: components["schemas"]["RoleEnum"] | components["schemas"]["BlankEnum"];
        };
        AgentUserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            role?: components["schemas"]["RoleEnum"] | components["schemas"]["BlankEnum"];
        };
        /** @enum {unknown} */
        BlankEnum: "";
        Customer: {
            readonly id: number;
            readonly total_orders: string;
            readonly agent_name: string;
            name: string;
            address: string;
            contact: string;
            agent: number;
        };
        CustomerRequest: {
            name: string;
            address: string;
            contact: string;
            agent: number;
        };
        Email: {
            /** Format: email */
            email: string;
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        Item: {
            readonly id: number;
            variants: components["schemas"]["ItemVariant"][];
            sizes: components["schemas"]["ItemSize"][];
            name: string;
            description?: string;
            /** Format: decimal */
            price: string;
            type?: (components["schemas"]["TypeEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: uuid */
            readonly qr_code: string;
        };
        ItemRequest: {
            variants: components["schemas"]["ItemVariantRequest"][];
            sizes: components["schemas"]["ItemSizeRequest"][];
            name: string;
            description?: string;
            /** Format: decimal */
            price: string;
            type?: (components["schemas"]["TypeEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        ItemSize: {
            readonly id: number;
            stock: number;
            size: string;
            readonly item: number;
        };
        ItemSizeRequest: {
            stock: number;
            size: string;
        };
        ItemVariant: {
            readonly id: number;
            color: string;
            /** Format: uri */
            image?: string | null;
            readonly item: number;
        };
        ItemVariantRequest: {
            color: string;
            /** Format: binary */
            image?: string | null;
        };
        LoginRequestRequest: {
            username?: string;
            /** Format: email */
            email?: string;
            password: string;
        };
        LoginResponse: {
            access: string;
            refresh: string;
            role: components["schemas"]["RoleEnum"];
            user_id: number;
        };
        /** @enum {unknown} */
        NullEnum: null;
        Order: {
            readonly id: number;
            readonly items: components["schemas"]["OrderItem"][];
            readonly total_quantity: string;
            readonly agent_details: components["schemas"]["SimpleAgent"];
            readonly customer_details: components["schemas"]["SimpleCustomer"];
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        OrderItem: {
            readonly id: number;
            readonly item: components["schemas"]["SimpleItem"];
            readonly variant: components["schemas"]["ItemVariant"];
            readonly size: components["schemas"]["ItemSize"];
            quantity: number;
            packed_quantity?: number;
            readonly order: number;
        };
        OrderItemRequest: {
            quantity: number;
            packed_quantity?: number;
        };
        OrderRequest: {
            customer: number;
            agent: number;
            status?: components["schemas"]["StatusEnum"];
        };
        PasswordToken: {
            password: string;
            token: string;
        };
        PasswordTokenRequest: {
            password: string;
            token: string;
        };
        PatchedAdminRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username?: string;
            /** Format: email */
            email?: string;
            password?: string;
        };
        PatchedAgentRequest: {
            username?: string;
            /** Format: email */
            email?: string;
            password?: string;
            contact?: string;
        };
        PatchedCustomerRequest: {
            name?: string;
            address?: string;
            contact?: string;
            agent?: number;
        };
        PatchedItemRequest: {
            variants?: components["schemas"]["ItemVariantRequest"][];
            sizes?: components["schemas"]["ItemSizeRequest"][];
            name?: string;
            description?: string;
            /** Format: decimal */
            price?: string;
            type?: (components["schemas"]["TypeEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        PatchedItemSizeRequest: {
            stock?: number;
            size?: string;
        };
        PatchedItemVariantRequest: {
            color?: string;
            /** Format: binary */
            image?: string | null;
        };
        PatchedOrderRequest: {
            customer?: number;
            agent?: number;
            status?: components["schemas"]["StatusEnum"];
        };
        ResetToken: {
            token: string;
        };
        ResetTokenRequest: {
            token: string;
        };
        /**
         * @description * `ADMIN` - Admin
         *     * `AGENT` - Agent
         * @enum {string}
         */
        RoleEnum: "ADMIN" | "AGENT";
        SimpleAgent: {
            readonly id: number;
            username: string;
        };
        SimpleAgentRequest: {
            username: string;
        };
        SimpleCustomer: {
            readonly id: number;
            name: string;
        };
        SimpleCustomerRequest: {
            name: string;
        };
        SimpleItem: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            price: string;
        };
        SimpleItemRequest: {
            name: string;
            /** Format: decimal */
            price: string;
        };
        /**
         * @description * `PENDING` - Pending
         *     * `PACKED` - Packed
         *     * `DISPATCHED` - Dispatched
         * @enum {string}
         */
        StatusEnum: "PENDING" | "PACKED" | "DISPATCHED";
        /**
         * @description * `kids` - Kids
         *     * `gents` - Gents
         * @enum {string}
         */
        TypeEnum: "kids" | "gents";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admins_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin"][];
                };
            };
        };
    };
    admins_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminRequest"];
                "multipart/form-data": components["schemas"]["AdminRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin"];
                };
            };
        };
    };
    admins_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin"];
                };
            };
        };
    };
    admins_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminRequest"];
                "multipart/form-data": components["schemas"]["AdminRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin"];
                };
            };
        };
    };
    admins_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admins_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admin"];
                };
            };
        };
    };
    agents_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
        };
    };
    agents_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AgentRequest"];
                "multipart/form-data": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
        };
    };
    agents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
        };
    };
    agents_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AgentRequest"];
                "multipart/form-data": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
        };
    };
    agents_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agents_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAgentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAgentRequest"];
                "multipart/form-data": components["schemas"]["PatchedAgentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
        };
    };
    agents_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequestRequest"];
                "multipart/form-data": components["schemas"]["LoginRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    customers_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"][];
                };
            };
        };
    };
    customers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerRequest"];
                "multipart/form-data": components["schemas"]["CustomerRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerRequest"];
                "multipart/form-data": components["schemas"]["CustomerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomerRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomerRequest"];
                "multipart/form-data": components["schemas"]["PatchedCustomerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    dashboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    items_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
        };
    };
    items_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ItemRequest"];
                "multipart/form-data": components["schemas"]["ItemRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    items_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    items_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ItemRequest"];
                "multipart/form-data": components["schemas"]["ItemRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    items_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    items_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedItemRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedItemRequest"];
                "multipart/form-data": components["schemas"]["PatchedItemRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    items_by_qr_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
        };
    };
    items_item_size_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSize"][];
                };
            };
        };
    };
    items_item_size_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemSizeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ItemSizeRequest"];
                "multipart/form-data": components["schemas"]["ItemSizeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSize"];
                };
            };
        };
    };
    items_item_size_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item size. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSize"];
                };
            };
        };
    };
    items_item_size_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item size. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemSizeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ItemSizeRequest"];
                "multipart/form-data": components["schemas"]["ItemSizeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSize"];
                };
            };
        };
    };
    items_item_size_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item size. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    items_item_size_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item size. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedItemSizeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedItemSizeRequest"];
                "multipart/form-data": components["schemas"]["PatchedItemSizeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSize"];
                };
            };
        };
    };
    items_variants_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemVariant"][];
                };
            };
        };
    };
    items_variants_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemVariantRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ItemVariantRequest"];
                "multipart/form-data": components["schemas"]["ItemVariantRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemVariant"];
                };
            };
        };
    };
    items_variants_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item variant. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemVariant"];
                };
            };
        };
    };
    items_variants_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item variant. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemVariantRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ItemVariantRequest"];
                "multipart/form-data": components["schemas"]["ItemVariantRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemVariant"];
                };
            };
        };
    };
    items_variants_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item variant. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    items_variants_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this item variant. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedItemVariantRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedItemVariantRequest"];
                "multipart/form-data": components["schemas"]["PatchedItemVariantRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemVariant"];
                };
            };
        };
    };
    orders_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
        };
    };
    orders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderRequest"];
                "multipart/form-data": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_add_item_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddOrderItemRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AddOrderItemRequest"];
                "multipart/form-data": components["schemas"]["AddOrderItemRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    orders_delete_item_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderRequest"];
                "multipart/form-data": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOrderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOrderRequest"];
                "multipart/form-data": components["schemas"]["PatchedOrderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailRequest"];
                "multipart/form-data": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Email"];
                };
            };
        };
    };
    password_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordTokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordTokenRequest"];
                "multipart/form-data": components["schemas"]["PasswordTokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordToken"];
                };
            };
        };
    };
    password_validate_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetTokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ResetTokenRequest"];
                "multipart/form-data": components["schemas"]["ResetTokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetToken"];
                };
            };
        };
    };
}
