# Generated by Django 5.2.9 on 2025-12-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
