# Generated by Django 5.2.9 on 2026-02-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_color_remove_item_photo_remove_item_size_and_more'),
        ('orders', '0002_alter_order_status_delete_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.itemvariant'),
        ),
    ]
