# Generated by Django 5.2.9 on 2026-02-12 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_itemvariant_size_remove_itemvariant_stock_and_more'),
        ('orders', '0003_remove_orderitem_selected_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.itemsize'),
        ),
    ]
