# Generated by Django 5.2.14 on 2026-09-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_edit_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
