# Generated by Django 5.2.9 on 2025-12-23 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
