# Generated by Django 5.2.9 on 2026-03-14 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('kids', 'Kids'), ('gents', 'Gents')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
