# Generated by Django 5.2.9 on 2026-01-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
