# Generated by Django 5.2.9 on 2026-02-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_color_remove_item_photo_remove_item_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('kids', 'Kids'), ('gents', 'Gents')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='items.item')),
            ],
        ),
    ]
