# Generated by Django 5.2.9 on 2026-02-21 05:25

import apps.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_itemvariant_size_remove_itemvariant_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.items.models.item_variant_image_path),
        ),
    ]
