# Generated by Django 5.2.9 on 2026-03-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_itemvariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('kids', 'Kids'), ('gents', 'Gents')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size',
            field=models.CharField(choices=[('20-24', '20-24'), ('26-30', '26-30'), ('32-36', '32-36'), ('38', '38'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='itemsize',
            unique_together={('item', 'size')},
        ),
    ]
